### PR TITLE
SC 1403 Individual People Page

### PR DESCRIPTION
**Pull request by shhivam**
Currently individuals are located at  `/people/#akshay-gupta`  (i.e. an HTML anchor) but this PR moves them to their own dedicated page `/people/akshay-gupta` 

Figma link: https://www.figma.com/file/aFV2NmKJeArRMceHqwoIWX/Nilenso?node-id=0%3A1&t=Knk8It1CGGnhjl8U-0

## Desktop View
image

## Mobile View
image

### CODE REVIEW

**Comment by tfidfwastaken** [comment]
There are some deviations from the [design](https://www.figma.com/file/aFV2NmKJeArRMceHqwoIWX/Nilenso?node-id=1296%3A274&t=M5QOlKzmzEBrRXMa-4).

* No whitespace margins and the back arrow is aligned with the DP instead of being on the edges.
* Vertical separator between DP and bio text.
* Icons are different from the design and aligned in the centre instead of left-aligned.
* The person's name is in a lighter font and pink. The nick is part of the name, whereas, in the design, it's part of the subtitle.
* Footer looks different.

I know the last one is intended based on a previous discussion. Are the other changes also intentional? If not, let's make them match. If they are intentional, please explain why the design needs to be tweaked.

Putting the original design and current view for side-to-side comparison.

image
image

**Comment by shhivam** [comment]
Comments resolved

**Comment by tfidfwastaken** [comment]
It's looking good, Shivam!

I want to request a few more changes, though.

This font should be pure black colour, weight 500. And not a blocker, but the nickname in the design is actually a smaller font, but in the interest of time, I'm okay with it being the same.
image

There's also a copywriting error. `Our tribe` shows up twice here:
image

I would also like to see some more whitespace/margin to the right of the bio text.
Current:
image

Preferred/more representative of the design:
image

**Comment by shhivam** [comment]
Let me quickly fix these

**Comment by shhivam** [comment]
Fixed these

**Review by vkrmis — APPROVED** [review]
Looks good

**Review by tfidfwastaken — APPROVED** [review]

**Pull request merged**
